### ISSUE TITLE
mfc.set_flow_rate() returning error when used with Alicat MCVS

### ISSUE THREAD

**Issue by grj336** [numat/alicat#13]
I have a setup that uses 2 Alicat MCVS MFCs (MCVS-500SCCM-D/5M), 1 MC and 1 Flow Meter (M). I can initialise all the devices fine and can change various settings (ie change gas), and get a response from mfc.get(). However, when updating the MCVS's, I get an error (see below):
```
mfc11.set_flow_rate(1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/alicat/serial.py", line 273, in set_flow_rate  self._set_control_point('flow', retries)
  File "/usr/local/lib/python3.7/dist-packages/alicat/serial.py", line 334, in _set_control_point
    value = int(line.split('=')[-1])
ValueError: invalid literal for int() with base 10: 'B +014.74 +024.46 +0000.2 -0000.1 0000.0      N2'
```  
The MC MFC updates fine. Anyone else had issues here? 

For reference, here is the test code
``` python
from alicat import *

mfc11 = FlowController(port='/dev/ttyUSB0', address='B')
print(mfc11.get())
mfc12 = FlowController(port='/dev/ttyUSB0', address='A')
print(mfc12.get())

mfc11.set_flow_rate(1.0)
```

**Comment by patrickfuller** [comment]
Interesting!

This driver sets some lower-level registers in the Alicats, allowing you the undocumented feature of toggling between pressure and flow control. It looks like your Alicat doesn't have this ability. Let me add something to handle Alicats that can't toggle between these two control types.

**Comment by patrickfuller** [comment]
1fb7077229df00653b8ae8a9f87575319fbf265f should fix this. I updated on pypi. @grj336 - let me know if it works.

**Comment by DrewMeyersCUboulder** [comment]
I encountered this issue as well. It turned out that I needed to manually switch the set point source (navigate to Control->Advanced Control on the MFC screen) from analog to digital/serial. After that, I was able to change the flow rate via python.

**Comment by ptriteshvarma** [comment]
> [1fb7077](https://github.com/numat/alicat/commit/1fb7077229df00653b8ae8a9f87575319fbf265f) should fix this. I updated on pypi. @grj336 - let me know if it works.

Encountered same issue. Went back to the serial.py file to verify and looks like the changes are not  checked in.

**Comment by patrickfuller** [comment]
@ptriteshvarma I checked the [pypi source](https://pypi.org/project/alicat/#files) and 1fb7077 is included (version 0.2.9). What version are you running?

**Comment by ptriteshvarma** [comment]
I verified and I am using v 0.2.9. I tried to reinstall it and re-run the command "flow_controller.set_flow_rate(300)" and when I try to do so I am getting this message
"Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    flow_controller.set_flow_rate(300)
  File "C:\Users\ptrit\AppData\Local\Programs\Python\Python38\lib\site-packages\alicat\serial.py", line 274, in set_flow_rate
    self._set_setpoint(flow, retries)
  File "C:\Users\ptrit\AppData\Local\Programs\Python\Python38\lib\site-packages\alicat\serial.py", line 308, in _set_setpoint
    raise IOError("Could not set setpoint.")
OSError: Could not set setpoint."
The message says "Could not set setpoint." but when I look at the device the set point is changed. What do you think the reason would be ? 
Thanks for responding to my request.

**Comment by patrickfuller** [comment]
How old is the Alicat?

Their API has changed over time in subtle ways. In  this case, some older Alicats don’t respond to setpoint changes while some do.

The lazy fix is to wrap with a try/except OSError. I don’t have a better fix unfortunately, as it would break response validation on newer alicats.

**Comment by ptriteshvarma** [comment]
Sorry for the late late reply. Its was an really old Alicat MFC, I tried
with a new one and it works just fine. Thanks for the library and your
quick response. Again sorry for my late response
Regards,

*Ritesh Varma P.T*
Phone - (321) 961-3240
