### ISSUE TITLE
Where is tare flow ?

### ISSUE THREAD

**Issue by ahmadfarisfs** [numat/alicat#24]

**Comment by alexrudd2** [comment]
Hello Ahmad,

Current our version of the driver does not have any way to tare flow.  I haven't tested it myself, but believe @marinapalese implemented it in [her fork](https://github.com/marinapalese/alicat).  It's also possible to tare flow from the front panel.

**Comment by marinapalese** [comment]
Thanks @alexrudd2! Yes it is the tare_volumetric() function. The serial command it uses has existed for all mainline firmware, and I've tested all the code I wrote. Taring from the front panel depends a bit on the firmware - older controllers you had to fiddle with the auto tare for a one-time tare.

**Comment by patrickfuller** [comment]
Fixed by #15.
