### ISSUE TITLE
Custom Mix: could not convert string to float

### ISSUE THREAD

**Issue by pstanley-iss** [numat/alicat#32]
I am trying to communicate with an MFC which is using a custom mix of gas. I set up the mix on the MFC, but when reading the device via serial, I get the following error:

```
>>> print(flow_controller2.get())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/alicat/serial.py", line 389, in get
    state = FlowMeter.get(self, retries)
  File "/home/pi/.local/lib/python3.9/site-packages/alicat/serial.py", line 126, in get
    return {k: (v if k == self.keys[-1] else float(v))
  File "/home/pi/.local/lib/python3.9/site-packages/alicat/serial.py", line 126, in <dictcomp>
    return {k: (v if k == self.keys[-1] else float(v))
ValueError: could not convert string to float: 'Mix2'
```

**Comment by pstanley-iss** [comment]
I had assumed that it had to do with the custom mix, but when I switched to a standard gas (Ar), I get the same error. Using Python 3.9, Alicat v0.4.0, MFC firmware 8v33.0-R23

**Comment by alexrudd2** [comment]
Your description says "MFC", which I take to mean "Mass Flow _Controller_."

Is your code using the `FlowMeter` class or `FlowController`?

**Comment by pstanley-iss** [comment]
FlowController. 

Set-up code:
```
from alicat import FlowController
mfc = '/dev/serial/by-id/usb-FTDI_USB-RS232_Cable_AU05812G-if00-port0'
flow_controller2 = FlowController(port=mfc)
```

**Comment by alexrudd2** [comment]
OK.  I cannot troubleshoot this on real hardware for a while.

However, what happens if you try changing line 126 of `serial.py`?
from: `{k: (v if k == self.keys[-1] else float(v))`
to: `{k: (v if k == self.keys[-1] or isinstance(v, str) else float(v))`

**Comment by pstanley-iss** [comment]
That resolves the issue. All data looks correct.

**Comment by alexrudd2** [comment]
OK, great!  Please let me know if anything else is broken.  I can prepare an updated release for PyPI soon.   There are some other changes I need to do by early March anyway (upstream `pymodbus` is breaking API in the upcoming `3.2.0` release)

**Comment by alexrudd2** [comment]
@pstanley-iss

I realized that we've ripped out the changes I needed to make in March, so I released this fix on PyPI for you: https://pypi.org/project/alicat/0.4.1/
