### ISSUE TITLE
FlowMeter is_connected method in serial.py

### ISSUE THREAD

**Issue by Brad-Houska** [numat/alicat#7]
Hi, I'm new to GitHub (I'm an intern). I'm not sure if this is an issue, but I will report it in case:

In your _is_connected_ method, you assert that '_flow_setpoint_' is in '_device.keys_' to check if connected:

```
                if cls.__name__ == 'FlowMeter':
                    assert c and 'flow_setpoint' not in device.keys
                elif cls.__name__ == 'FlowController':
                    assert c and 'flow_setpoint' in device.keys
```

However, in your _FlowMeter_ constructor, you initialize '_setpoint_' instead of '_flow_setpoint_':

```
self.keys = ['pressure', 'temperature', 'volumetric_flow', 'mass_flow',
                     'setpoint', 'gas']
```

I do not see any line in your code where you could have added '_flow_setpoint_' to' _device.keys_'. This makes me think that _is_connected_ will always return False for _FlowController_ objects.

**Comment by patrickfuller** [comment]
You're right. I added in the ability for Alicats to control on either pressure or flow in 71f0fb8b1369766016efc863270721eb12a4f711, and renamed `flow_setpoint` to `setpoint`. I must have missed updating the `is_connected` method.

Do you want to try issuing a pull request to fix it?

**Comment by Brad-Houska** [comment]
One more thing: if you initialize a device as a _FlowMeter_ object that has _setpoint_ in _device.keys_, then _is_connected_ would return false. 
```
if cls.__name__ == 'FlowMeter':
                    assert c and 'flow_setpoint' not in device.keys
```
Do you think the statement is necessary? Because _FlowMeter_ can potentially contain _setpoint_  in _device.keys_, if a flow controller is initialized as a _FlowMeter_ object.

**Comment by Brad-Houska** [comment]
Yes I'll do the pull request

**Comment by Brad-Houska** [comment]
Ok. For now I'll just replace 'flow_setpoint' with 'setpoint'
